# Form implementation generated from reading ui file 'e:\demoalim\exitscreen\form.ui'
#
# Created by: PyQt6 UI code generator 6.3.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import os

stop=0



class Ui_Second_screen(object):
    def setupUi(self, Second_screen):
        Second_screen.setObjectName("Second_screen")
        Second_screen.resize(400, 200)
        Second_screen.setStyleSheet("background-color: rgb(255,255,255);\n"
"border-color: rgb(0, 0, 0);")
        self.label = QtWidgets.QLabel(Second_screen)
        self.label.setGeometry(QtCore.QRect(-20, -20, 441, 231))
        self.label.setStyleSheet("background-color: rgb(170, 0, 0);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.horizontalLayoutWidget = QtWidgets.QWidget(Second_screen)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(80, 90, 241, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.SI = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.SI.setStyleSheet("QPushButton{\n"
"    color: rgb(0,0,0);\n"
"    border:0px;\n"
"    border-right: 2 solid rgb(135, 0, 2);\n"
"    border-bottom: 4 solid rgb(135, 0, 2);\n"
"    border-radius:8px;\n"
"    background-color: rgb(210, 0, 3);\n"
"}\n"
"QPushButton:hover{\n"
"    color: rgb(0,0,0);\n"
"    border-right: 2 solid rgb(135, 0, 2);\n"
"    border-bottom: 4 solid rgb(135, 0, 2);\n"
"    border-radius:8px;\n"
"    background-color: rgb(190, 0, 0);\n"
"}\n"
"QPushButton:pressed{\n"
"    color: rgb(0,0,0);\n"
"    border:0px;\n"
"    border-right:0 solid rgb(135, 0, 2);\n"
"    border-bottom:0 solid rgb(135, 0, 2);\n"
"    border-left: 2 solid rgb(135, 0, 2);\n"
"    border-top: 4 solid rgb(135, 0, 2);\n"
"    border-radius:8px;\n"
"    background-color: rgb(190, 0, 0);\n"
"}")
        self.SI.setObjectName("SI")
        self.horizontalLayout.addWidget(self.SI)
        self.NO = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.NO.setStyleSheet("QPushButton{\n"
"    color: rgb(0,0,0);\n"
"    border:0px;\n"
"    border-right: 2 solid rgb(135, 0, 2);\n"
"    border-bottom: 4 solid rgb(135, 0, 2);\n"
"    border-radius:8px;\n"
"    background-color: rgb(210, 0, 3);\n"
"}\n"
"QPushButton:hover{\n"
"    color: rgb(0,0,0);\n"
"    border-right: 2 solid rgb(135, 0, 2);\n"
"    border-bottom: 4 solid rgb(135, 0, 2);\n"
"    border-radius:8px;\n"
"    background-color: rgb(190, 0, 0);\n"
"}\n"
"QPushButton:pressed{\n"
"    color: rgb(0,0,0);\n"
"    border:0px;\n"
"    border-right:0 solid rgb(135, 0, 2);\n"
"    border-bottom:0 solid rgb(135, 0, 2);\n"
"    border-left: 2 solid rgb(135, 0, 2);\n"
"    border-top: 4 solid rgb(135, 0, 2);\n"
"    border-radius:8px;\n"
"    background-color: rgb(190, 0, 0);\n"
"}")
        self.NO.setObjectName("NO")
        self.horizontalLayout.addWidget(self.NO)
        self.label_3 = QtWidgets.QLabel(Second_screen)
        self.label_3.setGeometry(QtCore.QRect(50, 40, 301, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(Second_screen)
        self.label_2.setGeometry(QtCore.QRect(30, 20, 341, 161))
        self.label_2.setStyleSheet("border-radius: 30px")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label.raise_()
        self.label_2.raise_()
        self.horizontalLayoutWidget.raise_()
        self.label_3.raise_()

        self.retranslateUi(Second_screen)
        QtCore.QMetaObject.connectSlotsByName(Second_screen)

        #PARTE MODIFICATA
        #LAMBDA PER PASSARE PARAMETRI ESTERNI (Second_screen)
        self.NO.clicked.connect(lambda:self.tasto_no(Second_screen))
        self.SI.clicked.connect(lambda:self.tasto_si(Second_screen))
    def tasto_no(self,Second_screen):
        global stop
        stop=0
        Second_screen.hide()

    def tasto_si(self,Second_screen):
        global stop
        stop=1
        Second_screen.hide()

    def retranslateUi(self, Second_screen):
        _translate = QtCore.QCoreApplication.translate
        Second_screen.setWindowTitle(_translate("Second_screen", "EXIT"))
        path = os.path.dirname(os.path.abspath(__file__))
        Second_screen.setWindowIcon(QtGui.QIcon((os.path.join(path, 'logo2.png'))))
        self.SI.setText(_translate("Second_screen", "SI"))
        self.NO.setText(_translate("Second_screen", "NO"))
        self.label_3.setText(_translate("Second_screen", "SEI SICURO DI FERMARE IL PROGRAMMA?"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Second_screen = QtWidgets.QWidget()
    ui = Ui_Second_screen()
    ui.setupUi(Second_screen)
    Second_screen.show()
    sys.exit(app.exec())
