# Form implementation generated from reading ui file 'e:\demoalim\form_v2.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import os

class Ui_TESTALIM(object):
    def setupUi(self, TESTALIM):
        TESTALIM.setObjectName("TESTALIM")
        TESTALIM.resize(1110, 600)
        TESTALIM.setAutoFillBackground(False)
        TESTALIM.setStyleSheet("background-color: rgb(255,255,255);\n"
"border-color: rgb(0, 0, 0);")
        self.line = QtWidgets.QFrame(TESTALIM)
        self.line.setGeometry(QtCore.QRect(320, 0, 2, 600))
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.line.setLineWidth(2)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(TESTALIM)
        self.line_2.setGeometry(QtCore.QRect(600, 0, 2, 600))
        self.line_2.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.line_2.setLineWidth(2)
        self.line_2.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_2.setObjectName("line_2")
        self.line_4 = QtWidgets.QFrame(TESTALIM)
        self.line_4.setGeometry(QtCore.QRect(320, 250, 280, 2))
        self.line_4.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.line_4.setLineWidth(2)
        self.line_4.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(TESTALIM)
        self.line_5.setGeometry(QtCore.QRect(600, 320, 600, 2))
        self.line_5.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.line_5.setLineWidth(2)
        self.line_5.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_5.setObjectName("line_5")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(TESTALIM)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(370, 20, 198, 131))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        self.label_3.setFont(font)
        self.label_3.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.label_3.setScaledContents(False)
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setWordWrap(False)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.lcd_trascorso = QtWidgets.QLCDNumber(self.verticalLayoutWidget_2)
        self.lcd_trascorso.setObjectName("lcd_trascorso")
        self.horizontalLayout_13.addWidget(self.lcd_trascorso)
        self.label_28 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_28.setMaximumSize(QtCore.QSize(40, 16777215))
        self.label_28.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_13.addWidget(self.label_28)
        self.verticalLayout_3.addLayout(self.horizontalLayout_13)
        self.salvataggi = QtWidgets.QPushButton(TESTALIM)
        self.salvataggi.setGeometry(QtCore.QRect(10, 568, 301, 21))
        self.salvataggi.setStyleSheet("QPushButton{\n"
"    color: rgb(0,0,0);\n"
"    border:0px;\n"
"    border-right: 2 solid rgb(135, 0, 2);\n"
"    border-bottom: 4 solid rgb(135, 0, 2);\n"
"    border-radius:8px;\n"
"    background-color: rgb(210, 0, 3);\n"
"}\n"
"QPushButton:hover{\n"
"    color: rgb(0,0,0);\n"
"    border-right: 2 solid rgb(135, 0, 2);\n"
"    border-bottom: 4 solid rgb(135, 0, 2);\n"
"    border-radius:8px;\n"
"    background-color: rgb(190, 0, 0);\n"
"}\n"
"QPushButton:pressed{\n"
"    color: rgb(0,0,0);\n"
"    border:0px;\n"
"    border-right:0 solid rgb(135, 0, 2);\n"
"    border-bottom:0 solid rgb(135, 0, 2);\n"
"    border-left: 2 solid rgb(135, 0, 2);\n"
"    border-top: 4 solid rgb(135, 0, 2);\n"
"    border-radius:8px;\n"
"    background-color: rgb(190, 0, 0);\n"
"}")
        self.salvataggi.setObjectName("salvataggi")
        self.verticalLayoutWidget = QtWidgets.QWidget(TESTALIM)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(630, 200, 201, 101))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.start_on = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.start_on.setStyleSheet("QPushButton{\n"
"    color: rgb(0,0,0);\n"
"    border:0px;\n"
"    border-right: 2 solid rgb(135, 0, 2);\n"
"    border-bottom: 4 solid rgb(135, 0, 2);\n"
"    border-radius:8px;\n"
"    background-color: rgb(210, 0, 3);\n"
"}\n"
"QPushButton:hover{\n"
"    color: rgb(0,0,0);\n"
"    border-right: 2 solid rgb(135, 0, 2);\n"
"    border-bottom: 4 solid rgb(135, 0, 2);\n"
"    border-radius:8px;\n"
"    background-color: rgb(190, 0, 0);\n"
"}\n"
"QPushButton:pressed{\n"
"    color: rgb(0,0,0);\n"
"    border:0px;\n"
"    border-right:0 solid rgb(135, 0, 2);\n"
"    border-bottom:0 solid rgb(135, 0, 2);\n"
"    border-left: 2 solid rgb(135, 0, 2);\n"
"    border-top: 4 solid rgb(135, 0, 2);\n"
"    border-radius:8px;\n"
"    background-color: rgb(190, 0, 0);\n"
"}")
        self.start_on.setObjectName("start_on")
        self.horizontalLayout_4.addWidget(self.start_on)
        self.start_off = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.start_off.setStyleSheet("QPushButton{\n"
"    color: rgb(0,0,0);\n"
"    border:0px;\n"
"    border-right: 2 solid rgb(135, 0, 2);\n"
"    border-bottom: 4 solid rgb(135, 0, 2);\n"
"    border-radius:8px;\n"
"    background-color: rgb(210, 0, 3);\n"
"}\n"
"QPushButton:hover{\n"
"    color: rgb(0,0,0);\n"
"    border-right: 2 solid rgb(135, 0, 2);\n"
"    border-bottom: 4 solid rgb(135, 0, 2);\n"
"    border-radius:8px;\n"
"    background-color: rgb(190, 0, 0);\n"
"}\n"
"QPushButton:pressed{\n"
"    color: rgb(0,0,0);\n"
"    border:0px;\n"
"    border-right:0 solid rgb(135, 0, 2);\n"
"    border-bottom:0 solid rgb(135, 0, 2);\n"
"    border-left: 2 solid rgb(135, 0, 2);\n"
"    border-top: 4 solid rgb(135, 0, 2);\n"
"    border-radius:8px;\n"
"    background-color: rgb(190, 0, 0);\n"
"}")
        self.start_off.setObjectName("start_off")
        self.horizontalLayout_4.addWidget(self.start_off)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(TESTALIM)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(340, 160, 241, 51))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.ciclo_npw = QtWidgets.QLCDNumber(self.horizontalLayoutWidget_4)
        self.ciclo_npw.setObjectName("ciclo_npw")
        self.horizontalLayout_5.addWidget(self.ciclo_npw)
        self.label_6 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_6.setMinimumSize(QtCore.QSize(0, 0))
        self.label_6.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        self.ciclo_target = QtWidgets.QLCDNumber(self.horizontalLayoutWidget_4)
        self.ciclo_target.setObjectName("ciclo_target")
        self.horizontalLayout_5.addWidget(self.ciclo_target)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(TESTALIM)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(630, 20, 201, 131))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("background-color: rgba(255, 255, 255,0);")
        self.label_8.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.label_8.setScaledContents(False)
        self.label_8.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_8.setWordWrap(False)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_5.addWidget(self.label_8)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.lcd_mancante = QtWidgets.QLCDNumber(self.verticalLayoutWidget_4)
        self.lcd_mancante.setObjectName("lcd_mancante")
        self.horizontalLayout_14.addWidget(self.lcd_mancante)
        self.label_29 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_29.setMaximumSize(QtCore.QSize(40, 16777215))
        self.label_29.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_14.addWidget(self.label_29)
        self.verticalLayout_5.addLayout(self.horizontalLayout_14)
        self.horizontalLayoutWidget_6 = QtWidgets.QWidget(TESTALIM)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(350, 360, 221, 61))
        self.horizontalLayoutWidget_6.setObjectName("horizontalLayoutWidget_6")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_10 = QtWidgets.QLabel(self.horizontalLayoutWidget_6)
        self.label_10.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_7.addWidget(self.label_10)
        self.lcd_A = QtWidgets.QLCDNumber(self.horizontalLayoutWidget_6)
        self.lcd_A.setMinimumSize(QtCore.QSize(120, 0))
        self.lcd_A.setSmallDecimalPoint(True)
        self.lcd_A.setProperty("intValue", 0)
        self.lcd_A.setObjectName("lcd_A")
        self.horizontalLayout_7.addWidget(self.lcd_A)
        self.label_11 = QtWidgets.QLabel(self.horizontalLayoutWidget_6)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_7.addWidget(self.label_11)
        self.horizontalLayoutWidget_7 = QtWidgets.QWidget(TESTALIM)
        self.horizontalLayoutWidget_7.setGeometry(QtCore.QRect(350, 440, 221, 61))
        self.horizontalLayoutWidget_7.setObjectName("horizontalLayoutWidget_7")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_7)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_12 = QtWidgets.QLabel(self.horizontalLayoutWidget_7)
        self.label_12.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_8.addWidget(self.label_12)
        self.lcd_W = QtWidgets.QLCDNumber(self.horizontalLayoutWidget_7)
        self.lcd_W.setMinimumSize(QtCore.QSize(120, 0))
        self.lcd_W.setSmallDecimalPoint(True)
        self.lcd_W.setObjectName("lcd_W")
        self.horizontalLayout_8.addWidget(self.lcd_W)
        self.label_13 = QtWidgets.QLabel(self.horizontalLayoutWidget_7)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_8.addWidget(self.label_13)
        self.horizontalLayoutWidget_8 = QtWidgets.QWidget(TESTALIM)
        self.horizontalLayoutWidget_8.setGeometry(QtCore.QRect(350, 510, 221, 61))
        self.horizontalLayoutWidget_8.setObjectName("horizontalLayoutWidget_8")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_8)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_14 = QtWidgets.QLabel(self.horizontalLayoutWidget_8)
        self.label_14.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_9.addWidget(self.label_14)
        self.lcd_ohm = QtWidgets.QLCDNumber(self.horizontalLayoutWidget_8)
        self.lcd_ohm.setMinimumSize(QtCore.QSize(120, 0))
        self.lcd_ohm.setSmallDecimalPoint(True)
        self.lcd_ohm.setObjectName("lcd_ohm")
        self.horizontalLayout_9.addWidget(self.lcd_ohm)
        self.label_15 = QtWidgets.QLabel(self.horizontalLayoutWidget_8)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_9.addWidget(self.label_15)
        self.horizontalLayoutWidget_9 = QtWidgets.QWidget(TESTALIM)
        self.horizontalLayoutWidget_9.setGeometry(QtCore.QRect(350, 290, 221, 61))
        self.horizontalLayoutWidget_9.setObjectName("horizontalLayoutWidget_9")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_9)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_16 = QtWidgets.QLabel(self.horizontalLayoutWidget_9)
        font = QtGui.QFont()
        font.setBold(False)
        self.label_16.setFont(font)
        self.label_16.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_10.addWidget(self.label_16)
        self.lcd_v = QtWidgets.QLCDNumber(self.horizontalLayoutWidget_9)
        self.lcd_v.setMinimumSize(QtCore.QSize(120, 0))
        self.lcd_v.setSmallDecimalPoint(True)
        self.lcd_v.setObjectName("lcd_v")
        self.horizontalLayout_10.addWidget(self.lcd_v)
        self.label_17 = QtWidgets.QLabel(self.horizontalLayoutWidget_9)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_10.addWidget(self.label_17)
        self.horizontalLayoutWidget_15 = QtWidgets.QWidget(TESTALIM)
        self.horizontalLayoutWidget_15.setGeometry(QtCore.QRect(30, 70, 261, 51))
        self.horizontalLayoutWidget_15.setObjectName("horizontalLayoutWidget_15")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_15)
        self.horizontalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem)
        self.label_22 = QtWidgets.QLabel(self.horizontalLayoutWidget_15)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_18.addWidget(self.label_22)
        self.n_cicli = QtWidgets.QLineEdit(self.horizontalLayoutWidget_15)
        self.n_cicli.setStyleSheet("border-radius: 5px;\n"
"border:1px solid black;")
        self.n_cicli.setObjectName("n_cicli")
        self.horizontalLayout_18.addWidget(self.n_cicli)
        self.n_cicli.raise_()
        self.label_22.raise_()
        self.label_24 = QtWidgets.QLabel(TESTALIM)
        self.label_24.setGeometry(QtCore.QRect(900, 50, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        self.label_24.setFont(font)
        self.label_24.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.label_24.setScaledContents(False)
        self.label_24.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_24.setWordWrap(False)
        self.label_24.setObjectName("label_24")
        self.label_7 = QtWidgets.QLabel(TESTALIM)
        self.label_7.setEnabled(True)
        self.label_7.setGeometry(QtCore.QRect(0, 10, 81, 81))
        self.label_7.setStyleSheet("border-radius: 40px\n"
"")
        path = os.path.dirname(os.path.abspath(__file__))
        self.label_7.setPixmap(QtGui.QPixmap(os.path.join(path, 'elite.png')))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.tableWidget = QtWidgets.QTableWidget(TESTALIM)
        self.tableWidget.setGeometry(QtCore.QRect(50, 310, 221, 221))
        self.tableWidget.setAutoFillBackground(False)
        self.tableWidget.setStyleSheet("background-color: rgba(255, 0, 0,20);\n"
"border: 2px solid red;\n"
"")
        self.tableWidget.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.tableWidget.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.tableWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOn)
        self.tableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustToContents)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(35)
        self.tableWidget.verticalHeader().setDefaultSectionSize(30)
        self.tableWidget.verticalHeader().setMinimumSectionSize(24)
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(TESTALIM)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(30, 130, 261, 171))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_9 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.label_9.setMinimumSize(QtCore.QSize(120, 10))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_3.addWidget(self.label_9)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.tempo = QtWidgets.QLineEdit(self.verticalLayoutWidget_6)
        self.tempo.setStyleSheet("border-radius: 5px;\n"
"border:1px solid black;")
        self.tempo.setObjectName("tempo")
        self.horizontalLayout_3.addWidget(self.tempo)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_18 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.label_18.setMinimumSize(QtCore.QSize(120, 10))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_18.setFont(font)
        self.label_18.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_12.addWidget(self.label_18)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem2)
        self.potenza = QtWidgets.QLineEdit(self.verticalLayoutWidget_6)
        self.potenza.setStyleSheet("border-radius: 5px;\n"
"border:1px solid black;")
        self.potenza.setObjectName("potenza")
        self.horizontalLayout_12.addWidget(self.potenza)
        self.verticalLayout.addLayout(self.horizontalLayout_12)
        self.aggiungi = QtWidgets.QPushButton(self.verticalLayoutWidget_6)
        self.aggiungi.setStyleSheet("QPushButton{\n"
"    color: rgb(0,0,0);\n"
"    border:0px;\n"
"    border-right: 2 solid rgb(135, 0, 2);\n"
"    border-bottom: 4 solid rgb(135, 0, 2);\n"
"    border-radius:8px;\n"
"    background-color: rgb(210, 0, 3);\n"
"}\n"
"QPushButton:hover{\n"
"    color: rgb(0,0,0);\n"
"    border-right: 2 solid rgb(135, 0, 2);\n"
"    border-bottom: 4 solid rgb(135, 0, 2);\n"
"    border-radius:8px;\n"
"    background-color: rgb(190, 0, 0);\n"
"}\n"
"QPushButton:pressed{\n"
"    color: rgb(0,0,0);\n"
"    border:0px;\n"
"    border-right:0 solid rgb(135, 0, 2);\n"
"    border-bottom:0 solid rgb(135, 0, 2);\n"
"    border-left: 2 solid rgb(135, 0, 2);\n"
"    border-top: 4 solid rgb(135, 0, 2);\n"
"    border-radius:8px;\n"
"    background-color: rgb(190, 0, 0);\n"
"}")
        self.aggiungi.setObjectName("aggiungi")
        self.verticalLayout.addWidget(self.aggiungi)
        self.elimina = QtWidgets.QPushButton(self.verticalLayoutWidget_6)
        self.elimina.setStyleSheet("QPushButton{\n"
"    color: rgb(0,0,0);\n"
"    border:0px;\n"
"    border-right: 2 solid rgb(135, 0, 2);\n"
"    border-bottom: 4 solid rgb(135, 0, 2);\n"
"    border-radius:8px;\n"
"    background-color: rgb(210, 0, 3);\n"
"}\n"
"QPushButton:hover{\n"
"    color: rgb(0,0,0);\n"
"    border-right: 2 solid rgb(135, 0, 2);\n"
"    border-bottom: 4 solid rgb(135, 0, 2);\n"
"    border-radius:8px;\n"
"    background-color: rgb(190, 0, 0);\n"
"}\n"
"QPushButton:pressed{\n"
"    color: rgb(0,0,0);\n"
"    border:0px;\n"
"    border-right:0 solid rgb(135, 0, 2);\n"
"    border-bottom:0 solid rgb(135, 0, 2);\n"
"    border-left: 2 solid rgb(135, 0, 2);\n"
"    border-top: 4 solid rgb(135, 0, 2);\n"
"    border-radius:8px;\n"
"    background-color: rgb(190, 0, 0);\n"
"}")
        self.elimina.setObjectName("elimina")
        self.verticalLayout.addWidget(self.elimina)
        self.label_19 = QtWidgets.QLabel(TESTALIM)
        self.label_19.setGeometry(QtCore.QRect(10, 50, 291, 501))
        self.label_19.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 30px")
        self.label_19.setText("")
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(TESTALIM)
        self.label_20.setGeometry(QtCore.QRect(610, 190, 241, 121))
        self.label_20.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 30px")
        self.label_20.setText("")
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(TESTALIM)
        self.label_21.setGeometry(QtCore.QRect(610, 10, 241, 161))
        self.label_21.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 30px")
        self.label_21.setText("")
        self.label_21.setObjectName("label_21")
        self.label_23 = QtWidgets.QLabel(TESTALIM)
        self.label_23.setGeometry(QtCore.QRect(330, 10, 261, 221))
        self.label_23.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 30px")
        self.label_23.setText("")
        self.label_23.setObjectName("label_23")
        self.label_25 = QtWidgets.QLabel(TESTALIM)
        self.label_25.setGeometry(QtCore.QRect(880, 40, 221, 251))
        self.label_25.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 30px")
        self.label_25.setText("")
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(TESTALIM)
        self.label_26.setGeometry(QtCore.QRect(330, 270, 261, 321))
        self.label_26.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 30px")
        self.label_26.setText("")
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(TESTALIM)
        self.label_27.setGeometry(QtCore.QRect(-90, -40, 1211, 750))
        self.label_27.setStyleSheet("background-color: rgb(170, 0, 0);")
        self.label_27.setText("")
        self.label_27.setObjectName("label_27")
        self.led_ocp = QtWidgets.QLabel(TESTALIM)
        self.led_ocp.setGeometry(QtCore.QRect(900, 210, 20, 20))
        self.led_ocp.setStyleSheet("background-color: rgb(180, 0, 0);\n"
"border-radius:10px;")
        self.led_ocp.setText("")
        self.led_ocp.setObjectName("led_ocp")
        self.layoutWidget_2 = QtWidgets.QWidget(TESTALIM)
        self.layoutWidget_2.setGeometry(QtCore.QRect(890, 130, 195, 51))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.ovp_off = QtWidgets.QPushButton(self.layoutWidget_2)
        self.ovp_off.setStyleSheet("QPushButton{\n"
"    color: rgb(0,0,0);\n"
"    border:0px;\n"
"    border-right: 2 solid rgb(135, 0, 2);\n"
"    border-bottom: 4 solid rgb(135, 0, 2);\n"
"    border-radius:8px;\n"
"    background-color: rgb(210, 0, 3);\n"
"}\n"
"QPushButton:hover{\n"
"    color: rgb(0,0,0);\n"
"    border-right: 2 solid rgb(135, 0, 2);\n"
"    border-bottom: 4 solid rgb(135, 0, 2);\n"
"    border-radius:8px;\n"
"    background-color: rgb(190, 0, 0);\n"
"}\n"
"QPushButton:pressed{\n"
"    color: rgb(0,0,0);\n"
"    border:0px;\n"
"    border-right:0 solid rgb(135, 0, 2);\n"
"    border-bottom:0 solid rgb(135, 0, 2);\n"
"    border-left: 2 solid rgb(135, 0, 2);\n"
"    border-top: 4 solid rgb(135, 0, 2);\n"
"    border-radius:8px;\n"
"    background-color: rgb(190, 0, 0);\n"
"}")
        self.ovp_off.setObjectName("ovp_off")
        self.horizontalLayout_16.addWidget(self.ovp_off)
        self.ovp_on = QtWidgets.QPushButton(self.layoutWidget_2)
        self.ovp_on.setStyleSheet("QPushButton{\n"
"    color: rgb(0,0,0);\n"
"    border:0px;\n"
"    border-right: 2 solid rgb(135, 0, 2);\n"
"    border-bottom: 4 solid rgb(135, 0, 2);\n"
"    border-radius:8px;\n"
"    background-color: rgb(210, 0, 3);\n"
"}\n"
"QPushButton:hover{\n"
"    color: rgb(0,0,0);\n"
"    border-right: 2 solid rgb(135, 0, 2);\n"
"    border-bottom: 4 solid rgb(135, 0, 2);\n"
"    border-radius:8px;\n"
"    background-color: rgb(190, 0, 0);\n"
"}\n"
"QPushButton:pressed{\n"
"    color: rgb(0,0,0);\n"
"    border:0px;\n"
"    border-right:0 solid rgb(135, 0, 2);\n"
"    border-bottom:0 solid rgb(135, 0, 2);\n"
"    border-left: 2 solid rgb(135, 0, 2);\n"
"    border-top: 4 solid rgb(135, 0, 2);\n"
"    border-radius:8px;\n"
"    background-color: rgb(190, 0, 0);\n"
"}")
        self.ovp_on.setObjectName("ovp_on")
        self.horizontalLayout_16.addWidget(self.ovp_on)
        self.led_ovp = QtWidgets.QLabel(TESTALIM)
        self.led_ovp.setGeometry(QtCore.QRect(900, 80, 20, 20))
        self.led_ovp.setStyleSheet("background-color: rgb(180, 0, 0);\n"
"border-radius:10px;")
        self.led_ovp.setText("")
        self.led_ovp.setObjectName("led_ovp")
        self.layoutWidget = QtWidgets.QWidget(TESTALIM)
        self.layoutWidget.setGeometry(QtCore.QRect(930, 100, 151, 36))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_30 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.horizontalLayout_15.addWidget(self.label_30)
        self.ovp_line = QtWidgets.QLineEdit(self.layoutWidget)
        self.ovp_line.setStyleSheet("border-radius: 5px;\n"
"border:1px solid black;")
        self.ovp_line.setText("")
        self.ovp_line.setObjectName("ovp_line")
        self.horizontalLayout_15.addWidget(self.ovp_line)
        self.layoutWidget_3 = QtWidgets.QWidget(TESTALIM)
        self.layoutWidget_3.setGeometry(QtCore.QRect(930, 200, 151, 36))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_33 = QtWidgets.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.horizontalLayout_17.addWidget(self.label_33)
        self.ocp = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.ocp.setStyleSheet("border-radius: 5px;\n"
"border:1px solid black;")
        self.ocp.setText("")
        self.ocp.setObjectName("ocp")
        self.horizontalLayout_17.addWidget(self.ocp)
        self.layoutWidget_4 = QtWidgets.QWidget(TESTALIM)
        self.layoutWidget_4.setGeometry(QtCore.QRect(890, 230, 195, 51))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.layoutWidget_4)
        self.horizontalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.ocp_off = QtWidgets.QPushButton(self.layoutWidget_4)
        self.ocp_off.setStyleSheet("QPushButton{\n"
"    color: rgb(0,0,0);\n"
"    border:0px;\n"
"    border-right: 2 solid rgb(135, 0, 2);\n"
"    border-bottom: 4 solid rgb(135, 0, 2);\n"
"    border-radius:8px;\n"
"    background-color: rgb(210, 0, 3);\n"
"}\n"
"QPushButton:hover{\n"
"    color: rgb(0,0,0);\n"
"    border-right: 2 solid rgb(135, 0, 2);\n"
"    border-bottom: 4 solid rgb(135, 0, 2);\n"
"    border-radius:8px;\n"
"    background-color: rgb(190, 0, 0);\n"
"}\n"
"QPushButton:pressed{\n"
"    color: rgb(0,0,0);\n"
"    border:0px;\n"
"    border-right:0 solid rgb(135, 0, 2);\n"
"    border-bottom:0 solid rgb(135, 0, 2);\n"
"    border-left: 2 solid rgb(135, 0, 2);\n"
"    border-top: 4 solid rgb(135, 0, 2);\n"
"    border-radius:8px;\n"
"    background-color: rgb(190, 0, 0);\n"
"}")
        self.ocp_off.setObjectName("ocp_off")
        self.horizontalLayout_19.addWidget(self.ocp_off)
        self.ocp_on = QtWidgets.QPushButton(self.layoutWidget_4)
        self.ocp_on.setStyleSheet("QPushButton{\n"
"    color: rgb(0,0,0);\n"
"    border:0px;\n"
"    border-right: 2 solid rgb(135, 0, 2);\n"
"    border-bottom: 4 solid rgb(135, 0, 2);\n"
"    border-radius:8px;\n"
"    background-color: rgb(210, 0, 3);\n"
"}\n"
"QPushButton:hover{\n"
"    color: rgb(0,0,0);\n"
"    border-right: 2 solid rgb(135, 0, 2);\n"
"    border-bottom: 4 solid rgb(135, 0, 2);\n"
"    border-radius:8px;\n"
"    background-color: rgb(190, 0, 0);\n"
"}\n"
"QPushButton:pressed{\n"
"    color: rgb(0,0,0);\n"
"    border:0px;\n"
"    border-right:0 solid rgb(135, 0, 2);\n"
"    border-bottom:0 solid rgb(135, 0, 2);\n"
"    border-left: 2 solid rgb(135, 0, 2);\n"
"    border-top: 4 solid rgb(135, 0, 2);\n"
"    border-radius:8px;\n"
"    background-color: rgb(190, 0, 0);\n"
"}")
        self.ocp_on.setObjectName("ocp_on")
        self.horizontalLayout_19.addWidget(self.ocp_on)
        self.led_start = QtWidgets.QLabel(TESTALIM)
        self.led_start.setGeometry(QtCore.QRect(620, 240, 20, 20))
        self.led_start.setStyleSheet("background-color: rgb(180, 0, 0);\n"
"border-radius:10px;")
        self.led_start.setText("")
        self.led_start.setObjectName("led_start")
        self.collega_strumento = QtWidgets.QPushButton(TESTALIM)
        self.collega_strumento.setGeometry(QtCore.QRect(110, 20, 191, 24))
        self.collega_strumento.setStyleSheet("QPushButton{\n"
"    color: rgb(0,0,0);\n"
"    border:0px;\n"
"    border-right: 2 solid rgb(143, 0, 0);\n"
"    border-bottom: 4 solid rgb(143, 0, 0);\n"
"    border-radius:8px;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover{\n"
"    color: rgb(0,0,0);\n"
"    border-right: 2 solid rgb(143, 0, 0);\n"
"    border-bottom: 4 solid rgb(143, 0, 0);\n"
"    border-radius:8px;\n"
"    background-color: rgb(245, 245, 245);\n"
"}\n"
"QPushButton:pressed{\n"
"    color: rgb(0,0,0);\n"
"    border:0px;\n"
"    border-right:0 solid rgb(135, 0, 2);\n"
"    border-bottom:0 solid rgb(135, 0, 2);\n"
"    border-left: 2 solid rgb(143, 0, 0);\n"
"    border-top: 4 solid rgb(143, 0, 0);\n"
"    border-radius:8px;\n"
"    background-color: rgb(245, 245, 245);\n"
"}")
        self.collega_strumento.setObjectName("collega_strumento")
        self.line_6 = QtWidgets.QFrame(TESTALIM)
        self.line_6.setGeometry(QtCore.QRect(600, 180, 260, 2))
        self.line_6.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.line_6.setLineWidth(2)
        self.line_6.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_6.setObjectName("line_6")
        self.line_3 = QtWidgets.QFrame(TESTALIM)
        self.line_3.setGeometry(QtCore.QRect(860, -80, 2, 400))
        self.line_3.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.line_3.setLineWidth(2)
        self.line_3.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_3.setObjectName("line_3")
        self.frame = QtWidgets.QFrame(TESTALIM)
        self.frame.setGeometry(QtCore.QRect(609, 329, 491, 261))
        self.frame.setStyleSheet("border-radius:20px")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.label_27.raise_()
        self.label_25.raise_()
        self.label_19.raise_()
        self.label_26.raise_()
        self.label_23.raise_()
        self.label_21.raise_()
        self.label_20.raise_()
        self.line.raise_()
        self.line_2.raise_()
        self.line_4.raise_()
        self.line_5.raise_()
        self.verticalLayoutWidget_2.raise_()
        self.salvataggi.raise_()
        self.verticalLayoutWidget.raise_()
        self.horizontalLayoutWidget_4.raise_()
        self.verticalLayoutWidget_4.raise_()
        self.horizontalLayoutWidget_6.raise_()
        self.horizontalLayoutWidget_7.raise_()
        self.horizontalLayoutWidget_8.raise_()
        self.horizontalLayoutWidget_9.raise_()
        self.horizontalLayoutWidget_15.raise_()
        self.label_24.raise_()
        self.verticalLayoutWidget_6.raise_()
        self.label_7.raise_()
        self.tableWidget.raise_()
        self.led_ocp.raise_()
        self.layoutWidget_2.raise_()
        self.led_ovp.raise_()
        self.layoutWidget.raise_()
        self.layoutWidget_3.raise_()
        self.layoutWidget_4.raise_()
        self.led_start.raise_()
        self.collega_strumento.raise_()
        self.line_6.raise_()
        self.line_3.raise_()
        self.frame.raise_()

        self.retranslateUi(TESTALIM)
        QtCore.QMetaObject.connectSlotsByName(TESTALIM)

    def retranslateUi(self, TESTALIM):
        _translate = QtCore.QCoreApplication.translate
        TESTALIM.setWindowTitle(_translate("TESTALIM", "TEST ALIMENTATORE ELITE"))
        path = os.path.dirname(os.path.abspath(__file__))
        TESTALIM.setWindowIcon(QtGui.QIcon((os.path.join(path, 'logo2.png'))))
        self.label_3.setText(_translate("TESTALIM", "TEMPO TRASCORSO"))
        self.label_28.setText(_translate("TESTALIM", "MIN"))
        self.salvataggi.setText(_translate("TESTALIM", "Apri cartella salvataggi"))
        self.label_4.setText(_translate("TESTALIM", "START PROGRAMMA"))
        self.start_on.setText(_translate("TESTALIM", "ON"))
        self.start_off.setText(_translate("TESTALIM", "OFF"))
        self.label_5.setText(_translate("TESTALIM", "CICLO:"))
        self.label_6.setText(_translate("TESTALIM", "DI"))
        self.label_8.setText(_translate("TESTALIM", "TEMPO MANCANTE"))
        self.label_29.setText(_translate("TESTALIM", "MIN"))
        self.label_10.setText(_translate("TESTALIM", "CORRENTE   "))
        self.label_11.setText(_translate("TESTALIM", "A"))
        self.label_12.setText(_translate("TESTALIM", "POTENZA     "))
        self.label_13.setText(_translate("TESTALIM", "W"))
        self.label_14.setText(_translate("TESTALIM", "RESISTENZA "))
        self.label_15.setText(_translate("TESTALIM", "Ω"))
        self.label_16.setText(_translate("TESTALIM", "TENSIONE    "))
        self.label_17.setText(_translate("TESTALIM", "V"))
        self.label_22.setText(_translate("TESTALIM", "NUMERO CICLI:          "))
        self.label_24.setText(_translate("TESTALIM", "PROTEZIONE"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("TESTALIM", "TEMPO"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("TESTALIM", "POTENZA"))
        self.label_9.setText(_translate("TESTALIM", "TEMPO [sec]"))
        self.label_18.setText(_translate("TESTALIM", "POTENZA [W]"))
        self.aggiungi.setText(_translate("TESTALIM", "AGGIUNGI"))
        self.elimina.setText(_translate("TESTALIM", "ELIMINA L\'ULTIMA RIGA"))
        self.ovp_off.setText(_translate("TESTALIM", "OFF"))
        self.ovp_on.setText(_translate("TESTALIM", "ON"))
        self.label_30.setText(_translate("TESTALIM", "OVP"))
        self.label_33.setText(_translate("TESTALIM", "OCP"))
        self.ocp_off.setText(_translate("TESTALIM", "OFF"))
        self.ocp_on.setText(_translate("TESTALIM", "ON"))
        self.collega_strumento.setText(_translate("TESTALIM", "CONNETTI ALLO STRUMENTO"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TESTALIM = QtWidgets.QWidget()
    ui = Ui_TESTALIM()
    ui.setupUi(TESTALIM)
    TESTALIM.show()
    sys.exit(app.exec())
